import Head from "next/head";

import { DDragon } from "@fightmegg/riot-api";

import Cooldowns from "../components/Cooldowns";
import { Box, Heading } from "@chakra-ui/react";

export default function Home(props) {
  return (
    <Box w="100%">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" p={4}>
        <Heading>Patch: {props.version}</Heading>
        <Cooldowns data={props} />
      </Box>

      <Box as="footer">
        Site by: <a href="https://github.com/jeremiahfallin">@tacitician</a>
      </Box>
    </Box>
  );
}

export async function getStaticProps(context) {
  const ddragon = new DDragon();

  const champs = await ddragon.champion.all();
  const allChamps = await Promise.all(
    Object.keys(champs.data).map(async (championName) => {
      const champData = await ddragon.champion.byName({ championName });
      return champData;
    })
  );

  return {
    props: { version: champs.version, allChamps },
  };
}
